[package]
name = "tranquil-macros"
version = "0.1.0"
authors = ["Possseidon <xpossseidon@gmail.com>"]
edition = "2021"
description = "Macro crate for tranquil."
readme = "../README.md"
repository = "https://github.com/Possseidon/tranquil"
license = "MIT"
keywords = ["commands", "macro", "tranquil"]
categories = []

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
indoc = "1.0"
quote = "1.0"
syn = "1.0"
