[package]
name = "tranquil"
version = "0.1.0"
edition = "2021"

[dependencies]
tranquil-macros = { path = "../tranquil-macros" }
futures = "0.3.23"
serenity = "0.11.5"
tokio = { version = "1.21", features = ["macros", "rt-multi-thread", "signal"] }

[dev-dependencies]
dotenv = "0.15.0"
