[package]
name = "tranquil"
version = "0.2.0"
authors = ["Possseidon <xpossseidon@gmail.com>"]
edition = "2021"
description = "A module framework for Discord bots with slash commands, based on serenity."
readme = "../README.md"
repository = "https://github.com/Possseidon/tranquil"
license = "MIT"
keywords = ["bot", "commands", "discord", "framework", "serenity"]
categories = ["api-bindings"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1.64"
bounded-integer = { version = "0.5.3", features = ["types"] }
dotenvy = "0.15.5"
enumset = "1.0"
futures = { version = "0.3.23", default-features = false, features = [
    "async-await",
] }
serde = { version = "1.0", default-features = false }
serde_yaml = "0.9.13"
serde-tuple-vec-map = { version = "1.0", default-features = false }
serenity = { version = "0.11.5", default-features = false, features = [
    "client",
    "gateway",
    "model",
    "rustls_backend",
] }
tokio = { version = "1.21", default-features = false, features = ["signal"] }
tranquil-macros = { version = "0.2.0", path = "../tranquil-macros" }

[dev-dependencies]
indoc = "2.0"
tokio = { version = "1.21", default-features = false, features = [
    "rt-multi-thread",
] }
