[package]
name = "tranquil"
version = "0.1.0"
authors = ["Possseidon <xpossseidon@gmail.com>"]
edition = "2021"
description = "A module framework for Discord bots with slash commands, based on serenity."
readme = "../README.md"
repository = "https://github.com/Possseidon/tranquil"
license = "MIT"
keywords = ["bot", "commands", "discord", "framework", "serenity"]
categories = ["api-bindings"]

[dependencies]
tranquil-macros = { version = "0.1.0", path = "../tranquil-macros" }
bounded-integer = { version = "0.5.3", features = ["std", "macro", "types"] }
futures = "0.3.23"
serde = "1.0"
serenity = "0.11.5"
tokio = { version = "1.21", features = ["macros", "rt-multi-thread", "signal"] }
toml = "0.5.9"

[dev-dependencies]
dotenv = "0.15.0"
