name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: clippy
        run: cargo clippy --workspace --all-targets --verbose -- -D warnings
      - name: build
        run: cargo build --workspace --all-targets --verbose
      - name: test
        run: cargo test --workspace --all-targets --verbose

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fmt
        run: cargo fmt --all --check
